config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: 'employees#index'
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_secure_password
  has_many :work_histories, dependent: :destroy
  accepts_nested_attributes_for :work_histories, allow_destroy: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :login_emp
  before_action :login_required

  private

  def login_emp
    @login_emp ||= Employee.find_by(id: session[:employee_id]) if session[:employee_id]
  end

  def login_required
    redirect_to login_path unless login_emp
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  helper_method :fullname
  before_action :require_admin, only: [:new, :create, :destroy]

  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def edit
    @edit_profile =  params[:edit_profile]
    @employee = Employee.find(params[:id])
    require_yourself @employee
  end

  def create
    @employee = Employee.new(employee_params)
    set_default_password @employee

    if @employee.save
      redirect_to @employee, notice: "新しく「#{fullname @employee}さん」を登録しました。"
    else
      render :new
    end
  end

  def update
    @employee = Employee.find(params[:id])
    require_yourself @employee

    if @employee.update(employee_params)
      redirect_to @employee, notice: "「#{fullname @employee}さん」のプロフィールを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    employee = Employee.find(params[:id])
    redirect_to root_path, notice: "自分のことを削除することはできません。" if login_emp.id == employee.id
    employee.destroy
    redirect_to employees_url, notice: "「#{fullname employee}さん」を削除しました。"
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin, :team, :hobby, :comment,
    work_histories_attributes: [:id, :employee_id, :year, :company, :team, :mission, :_destroy])
  end

  def set_default_password employee
    employee.password = 'password'
    employee.password_confirmation = 'password'
  end

  def fullname e
    #ボツ案 破壊的メソッドだから繰り返し呼ばれたときに名前が伸びていく
    #e.last_name << ' ' << e.first_name

    #冗長すぎて嫌な案
    #str = ''
    #str << e.last_name
    #str << ' '
    #str << e.first_name

    #行けるけどいいのか微妙案
    e.last_name + ' ' + e.first_name
  end

  def require_admin
    redirect_to root_path unless login_emp.admin?
  end

  def require_yourself emp
    redirect_to root_path unless login_emp.id == emp.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    employee = Employee.find_by(email: session_params[:email])

    if employee&.authenticate(session_params[:password])
      session[:employee_id] = employee.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/employees/_edit_basic_info.html.haml
%h1 ユーザー管理

.nav.justify-content-end
  = link_to '一覧', employees_path, class: 'nav-link'

= render partial: 'form', locals: {employee: @employee}

app/views/employees/_edit_profile_info.html.haml
%h1 プロフィールの編集

.nav.justify-content-end
  = link_to '一覧', employees_path, class: 'nav-link'

- if employee.errors.present?
  %ul#error_explanation
    - employee.errors.full_messages.each do |msg|
      %li= msg

= form_with model: employee, local: true do |f|
  .form_group
    = f.label :team
    = f.text_field :team, class: 'form-control', id: 'team'
  .form_group
    = f.label :hobby
    = f.text_field :hobby, class: 'form-control', id: 'hobby'
  .form_group
    = f.label :comment
    = f.text_area :comment, row:5, class: 'form-control', id: 'comment'

  %hr.hr-primary

  ="職歴"
  %table.table.table-hover.table-striped
    %tbody
      %tr
        %th= "年数"
        %th= "企業"
        %th= "組織"
        %th= "ミッション"
        %th
      = f.nested_fields_for :work_histories, wrapper_tag: :tr do |h|
        %td= h.number_field :year, class: 'form-control'
        %td= h.text_field :company, class: 'form-control'
        %td= h.text_field :team, class: 'form-control'
        %td= h.text_field :mission, class: 'form-control'
        %td= h.remove_nested_fields_link '削除', class: 'btn btn-danger', role: 'button'
  = f.add_nested_fields_link :work_histories, '追加', class: 'btn btn-primary', role: 'button'

  %hr.hr-primary

  = f.submit nil, class: 'btn btn-primary'

app/views/employees/_form.html.haml
- if employee.errors.present?
  %ul#error_explanation
    - employee.errors.full_messages.each do |msg|
      %li= msg

= form_with model: employee, local: true do |f|
  .form_group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control', id: 'last_name'
  .form_group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control', id: 'first_name'
  .form_group
    = f.label :email
    = f.text_field :email, class: 'form-control', id: 'email'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      管理者権限
  = f.submit nil, class: 'btn btn-primary'

app/views/employees/edit.html.haml
-if @edit_profile
  = render partial: 'edit_profile_info', locals: {employee: @employee}
-else
  = render partial: 'edit_basic_info', locals: {employee: @employee}

app/views/employees/index.html.haml
%h1 社員一覧
- if login_emp.admin?
  = link_to '新規登録', new_employee_path, class: 'btn btn-primary'

.mb-3
%table.table.table-hover.table-striped
  %thead.thead-default
    %tr
      %th= '名前'
      %th= Employee.human_attribute_name(:team)
      %th
  %tbody
    - @employees.each do |e|
      %tr
        %td= link_to fullname(e), e
        %td= e.team
        - if login_emp.id == e.id
          %td= link_to 'プロフィールを編集する', edit_employee_path(e, edit_profile: true), class: 'btn btn-primary mr-3'
        - elsif login_emp.admin?
          %td= link_to '削除', e, method: :delete, data: {confirm: "#{fullname(e)} さんを削除しますか？"}, class: 'btn btn-danger mr-3'

app/views/employees/new.html.haml
%h1 新規登録

.nav.justify-content-end
  = link_to '一覧', employees_path, class: 'nav-link'

= render partial: 'form', locals: {employee: @employee}

app/views/employees/show.html.haml
%h1= fullname(@employee) + ' さんのプロフィール'

.nav.justify-content-end
  = link_to '一覧', employees_path, class: 'nav-link'

- if login_emp.id == @employee.id
  = link_to 'プロフィールを編集する', edit_employee_path(@employee, edit_profile: true), class: 'btn btn-primary mr-3'
  = link_to 'ユーザー管理', edit_employee_path(@employee), class: 'btn btn-warning mr-3'
- if login_emp.admin? && login_emp.id != @employee.id
  = link_to '削除', @employee, method: :delete, data: {confirm: "#{fullname(@employee)} さんを削除しますか？"}, class: 'btn btn-danger mr-3'

%hr.hr-primary

%p.text-info 基本情報
%table.table.table-hover.table-striped
  %tbody
    %tr
      %th= '名前'
      %td= fullname(@employee)
    %tr
      %th= Employee.human_attribute_name(:email)
      %td= @employee.email
    %tr
      %th= Employee.human_attribute_name(:team)
      %td= @employee.team
    %tr
      %th= Employee.human_attribute_name(:hobby)
      %td= @employee.hobby
    %tr
      %th= Employee.human_attribute_name(:comment)
      %td= @employee.comment

%p.text-info 職歴
%table.table.table-hover.table-striped
  %thead.thead-default
    %tr
      %th= '年数'
      %th= '所属'
      %th= 'ミッション'
    %tbody
      - @employee.work_histories.each do |h|
        %tr
          %td= h.year
          %td= h.company + " " + h.team
          %td= h.mission

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EmployeeProfile
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand E-Profiles

      #ul.navbar-nav.ml-auto
        - if login_emp
          #li.nav-item= link_to '社員一覧', employees_path, class: 'nav-link'
          #li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
          #li.nav-item.navbar-brand= "こんにちは。#{login_emp.last_name}さん"
        - else
          #li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-success
          = flash.notice
    = yield